server:
  port: 9003
eureka:
  client:
    register-with-eureka: false #不注册到Eureka,不在注册中心显示
    service-url:
      defaultZone: http://localhost:7001/eureka #,http://localhsot1:7002/eureka # 从哪个服务中心去拿服务。
feign:
   hystrix:
       enabled: true #开启熔断支持 true支持。
