server:
  port: 7002
eureka:
  instance:
    hostname: localhost1  #hostname
  client:
    serviceUrl:
      #defaultZone: http://localhost:7001/eureka

      defaultZone: http://localhost1:7002/eureka
    fetch-registry: false #是否到服务上抓取数据
    register-with-eureka: false #是否注册到注册中心
